name: "啊柚的碎碎念"
uid: "3493258856499557"
cookie_file: "~/.bilibili/cookie.txt"
download_root: "~/B站监控"

# QQ 通知
notify_target: "qq:65091C38C651B44BA071725FDF78A800"

# Whisper 转写
whisper_model: "medium"
whisper_device: "cuda"
transcribe_output_dir: "/mnt/e/情感素材库"
